// <auto-generated />
namespace Sellopedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedthedeliveryaddresstocart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedthedeliveryaddresstocart));
        
        string IMigrationMetadata.Id
        {
            get { return "202201251110230_Added the delivery address to cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
