// <auto-generated />
namespace Sellopedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addeduserreferencetocart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeduserreferencetocart));
        
        string IMigrationMetadata.Id
        {
            get { return "202201161354434_Added user reference to cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
